### ISSUE TITLE
Jest Issues

### ISSUE THREAD

**Issue by germs12** [peterluhub/xsm#2]
I am using your library in an Angular 7 app without any issues...except when it comes to testing.  I am getting the following error in all of my components where I'm importing the library:

```
import { set, bindState } from 'xsm';
```

# Full Error
```
 FAIL  app/another.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /another_app/node_modules/xsm/xsm.js:94
    export function set(key, val) {
    ^^^^^^

    SyntaxError: Unexpected token export

      2 | import { ActivatedRoute } from '@angular/router';
      3 | import styleString from './another.component.scss';
    > 4 | import { set, bindState } from 'xsm';
        | ^
      5 | import {
      6 |   AnotherComponent,
      7 |   AnotherModel,

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)

```

Any advice on how to resolve this?  Thank you!

**Comment by peterluhub** [comment]
This is a common issue with Jest and not unique to XSM.  If you search 'jest unexpected token import angular' on Google.  You will see many people having the same issue.

See this link for more info.
https://github.com/thymikee/jest-preset-angular/issues/277
